image: maven:3-amazoncorretto-11

build:
  before_script:
    - "echo \"<settings><servers><server><id>net.hep.ami-releases</id><username>${AMI_MAVEN_REPO_USERNAME}</username><password>${AMI_MAVEN_REPO_PASSWORD}</password></server></servers></settings>\" > ~/.m2/settings.xml"
  script:
    - "mvn deploy"
