#!/bin/sh
# chkconfig: - 50 50
# description: AMI Task Server

#############################################################################

THIS_SCRIPT=${BASH_SOURCE[0]:-$0}

while [[ -n $(readlink $THIS_SCRIPT) ]]
do
  THIS_SCRIPT=$(readlink $THIS_SCRIPT)
done

AMI_HOME=$(cd $(dirname $THIS_SCRIPT) && pwd)

#############################################################################

start() {
    sleep 2
    $AMI_HOME/startAMITaskServer.sh
}

stop() {
    sleep 2
    $AMI_HOME/stopAMITaskServer.sh
}

restart() {
    stop
    start
}

status() {
  if [[ -z $(ps -ef | grep "net\.hep\.ami\.task\.MainServer") ]]
  then
    printf "AMITaskServer:\t\t[stopped]\n"
  else
    printf "AMITaskServer:\t\t[running]\n"
  fi

  if [[ -z $(ps -ef | grep "watchDog\.sh") ]]
  then
    printf "WatchDog:\t\t[stopped]\n"
  else
    printf "WatchDog:\t\t[running]\n"
  fi
}

#############################################################################

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload|restart|condrestart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|reload|restart|condrestart|status}"
    exit 1
esac

#############################################################################

exit $?

#############################################################################
