
DROP VIEW IF EXISTS `FILE_VIEW`;;
DROP TABLE IF EXISTS `DATASET_FILE_BRIDGE`;;
DROP TABLE IF EXISTS `DATASET_PARAM`;;
DROP TABLE IF EXISTS `FILE`;;
DROP TABLE IF EXISTS `DATASET`;;
DROP TABLE IF EXISTS `FILE_TYPE`;;
DROP TABLE IF EXISTS `DATASET_TYPE`;;
DROP TABLE IF EXISTS `PROJECT`;;



CREATE TABLE `PROJECT` (
  `id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(512),
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(128) NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` VARCHAR(128) NOT NULL

) CHARSET=`utf8` COLLATE=`utf8_unicode_ci`;;

ALTER TABLE `PROJECT`
  ADD CONSTRAINT `pk1_PROJECT` PRIMARY KEY (`id`),
  ADD CONSTRAINT `uk1_PROJECT` UNIQUE KEY (`name`)
;;

ALTER TABLE `PROJECT`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT
;;



CREATE TABLE `DATASET_TYPE` (
  `id` INT NOT NULL,
  `projectFK` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(512),
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(128) NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` VARCHAR(128) NOT NULL

) CHARSET=`utf8` COLLATE=`utf8_unicode_ci`;;

ALTER TABLE `DATASET_TYPE`
  ADD CONSTRAINT `pk1_DATASET_TYPE` PRIMARY KEY (`id`),
  ADD CONSTRAINT `uk1_DATASET_TYPE` UNIQUE KEY (`name`, `projectFK`),
  ADD CONSTRAINT `fk1_DATASET_TYPE` FOREIGN KEY (`projectFK`) REFERENCES `PROJECT` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
;;

ALTER TABLE `DATASET_TYPE`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT
;;



CREATE TABLE `FILE_TYPE` (
  `id` INT NOT NULL,
  `projectFK` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(512),
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(128) NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` VARCHAR(128) NOT NULL

) CHARSET=`utf8` COLLATE=`utf8_unicode_ci`;;

ALTER TABLE `FILE_TYPE`
  ADD CONSTRAINT `pk1_FILE_TYPE` PRIMARY KEY (`id`),
  ADD CONSTRAINT `fk1_FILE_TYPE` FOREIGN KEY (`projectFK`) REFERENCES `PROJECT` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
;;

ALTER TABLE `FILE_TYPE`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT
;;



CREATE TABLE `DATASET` (
  `id` INT NOT NULL,
  `projectFK` INT NOT NULL,
  `typeFK` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(128) NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` VARCHAR(128) NOT NULL

) CHARSET=`utf8` COLLATE=`utf8_unicode_ci`;;

ALTER TABLE `DATASET`
  ADD CONSTRAINT `pk1_DATASET` PRIMARY KEY (`id`),
  ADD CONSTRAINT `uk1_DATASET` UNIQUE KEY (`name`, `projectFK`),
  ADD CONSTRAINT `fk1_DATASET` FOREIGN KEY (`projectFK`) REFERENCES `PROJECT` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk2_DATASET` FOREIGN KEY (`typeFK`) REFERENCES `DATASET_TYPE` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
;;

ALTER TABLE `DATASET`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT
;;



CREATE TABLE `FILE` (
  `id` INT NOT NULL,
  `typeFK` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(128) NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` VARCHAR(128) NOT NULL

) CHARSET=`utf8` COLLATE=`utf8_unicode_ci`;;

ALTER TABLE `FILE`
  ADD CONSTRAINT `pk1_FILE` PRIMARY KEY (`id`),
  ADD CONSTRAINT `uk1_FILE` UNIQUE KEY (`name`),
  ADD CONSTRAINT `fk1_FILE` FOREIGN KEY (`typeFK`) REFERENCES `FILE_TYPE` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
;;

ALTER TABLE `FILE`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT
;;



CREATE TABLE `DATASET_FILE_BRIDGE` (
  `id` INT NOT NULL,
  `datasetFK` INT NOT NULL,
  `fileFK` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(128) NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` VARCHAR(128) NOT NULL

) CHARSET=`utf8` COLLATE=`utf8_unicode_ci`;;

ALTER TABLE `DATASET_FILE_BRIDGE`
  ADD CONSTRAINT `pk1_DATASET_FILE_BRIDGE` PRIMARY KEY (`id`),
  ADD CONSTRAINT `fk1_DATASET_FILE_BRIDGE` FOREIGN KEY (`datasetFK`) REFERENCES `DATASET` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk2_DATASET_FILE_BRIDGE` FOREIGN KEY (`fileFK`) REFERENCES `FILE` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION

;;

ALTER TABLE `DATASET_FILE_BRIDGE`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT
;;



CREATE TABLE `DATASET_PARAM` (
  `id` INT NOT NULL,
  `datasetFK` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `type` VARCHAR(128) NOT NULL,
  `intValue` INT(11),
  `floatValue` DECIMAL(6,4),
  `stringValue` VARCHAR(512),
  `timestampValue` TIMESTAMP,
  `booleanValue` TINYINT(1) DEFAULT NULL,
  `blobValue` BLOB DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(128) NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` VARCHAR(128) NOT NULL

) CHARSET=`utf8` COLLATE=`utf8_unicode_ci`;;

ALTER TABLE `DATASET_PARAM`
  ADD CONSTRAINT `pk1_DATASET_PARAM` PRIMARY KEY (`id`),
  ADD CONSTRAINT `uk1_DATASET_PARAM` UNIQUE KEY (`name`, `datasetFK`),
  ADD CONSTRAINT `fk1_DATASET_PARAM` FOREIGN KEY (`datasetFK`) REFERENCES `DATASET` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
;;

ALTER TABLE `DATASET_PARAM`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT
;;

CREATE VIEW `FILE_VIEW` AS 
  SELECT `DATASET_FILE_BRIDGE`.`id` AS `id`, `PROJECT`.`name` AS `projectName`, `DATASET`.`name` AS `datasetName`,  `FILE`.`name` AS `fileName`
  FROM `PROJECT`, `DATASET`, `FILE`, `DATASET_FILE_BRIDGE`
  WHERE `DATASET`.`projectFK` = `PROJECT`.`id`
  AND `DATASET_FILE_BRIDGE`.`datasetFK` = `DATASET`.`id`
  AND `DATASET_FILE_BRIDGE`.`fileFK` = `FILE`.`id`
;;