-----------------------------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW "FILE_VIEW"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "DATASET_FILE_BRIDGE"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "DATASET_PARAM"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "FILE"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "DATASET_GRAPH"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "DATASET"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "FILE_TYPE"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "DATASET_TYPE"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "PROJECT"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -942 THEN
    RAISE;
  END IF;
END;
;;

-----------------------------------------------------------------------------

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE "seq_DATASET_FILE_BRIDGE"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE "seq_DATASET_PARAM"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE "seq_FILE"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE "seq_DATASET_GRAPH"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE "seq_DATASET"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE "seq_FILE_TYPE"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE "seq_DATASET_TYPE"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
;;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE "seq_PROJECT"';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -2289 THEN
    RAISE;
  END IF;
END;
;;

-----------------------------------------------------------------------------

CREATE TABLE "PROJECT" (
  "id" NUMBER(*, 0),
  "name" VARCHAR2(128),
  "description" VARCHAR2(512),
  "created" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "createdBy" VARCHAR2(128),
  "modified" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "modifiedBy" VARCHAR2(128)
);;

ALTER TABLE "PROJECT"
  ADD CONSTRAINT "pk1_PROJECT" PRIMARY KEY ("id")
;;

ALTER TABLE "PROJECT"
  ADD CONSTRAINT "uk1_PROJECT" UNIQUE ("name")
;;

ALTER TABLE "PROJECT"
  ADD CONSTRAINT "ck1_PROJECT" CHECK("id" IS NOT NULL)
;;

ALTER TABLE "PROJECT"
  ADD CONSTRAINT "ck2_PROJECT" CHECK("description" IS NOT NULL)
;;

ALTER TABLE "PROJECT"
  ADD CONSTRAINT "ck3_PROJECT" CHECK("created" IS NOT NULL)
;;

ALTER TABLE "PROJECT"
  ADD CONSTRAINT "ck4_PROJECT" CHECK("createdBy" IS NOT NULL)
;;

ALTER TABLE "PROJECT"
  ADD CONSTRAINT "ck5_PROJECT" CHECK("modified" IS NOT NULL)
;;

ALTER TABLE "PROJECT"
  ADD CONSTRAINT "ck6_PROJECT" CHECK("modifiedBy" IS NOT NULL)
;;

CREATE SEQUENCE "seq_PROJECT"
  START WITH 1 INCREMENT BY 1 CACHE 10
;;

CREATE TRIGGER "trig1_PROJECT"
  BEFORE INSERT ON "PROJECT"
  FOR EACH ROW
  BEGIN
    SELECT "seq_PROJECT".NEXTVAL INTO :NEW."id" FROM dual;
  END;
;;

CREATE TRIGGER "trig2_PROJECT"
  BEFORE UPDATE ON "PROJECT"
  FOR EACH ROW
  BEGIN
    :NEW."modified" := SYSDATE;
  END;
;;

-----------------------------------------------------------------------------

CREATE TABLE "DATASET_TYPE" (
  "id" NUMBER(*, 0),
  "projectFK" NUMBER(*, 0),
  "name" VARCHAR2(128),
  "description" VARCHAR2(512),
  "photo" CLOB,
  "video" CLOB,
  "animation" CLOB,
  "transparent" CLOB,
  "document" CLOB,
  "created" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "createdBy" VARCHAR2(128),
  "modified" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "modifiedBy" VARCHAR2(128)
);;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "pk1_DATASET_TYPE" PRIMARY KEY ("id")
;;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "uk1_DATASET_TYPE" UNIQUE ("name","projectFK")
;;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "ck1_DATASET_TYPE" CHECK("id" IS NOT NULL)
;;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "ck2_DATASET_TYPE" CHECK("projectFK" IS NOT NULL)
;;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "ck3_DATASET_TYPE" CHECK("name" IS NOT NULL)
;;


ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "ck4_DATASET_TYPE" CHECK("created" IS NOT NULL)
;;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "ck5_DATASET_TYPE" CHECK("createdBy" IS NOT NULL)
;;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "ck6_DATASET_TYPE" CHECK("modified" IS NOT NULL)
;;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "ck7_DATASET_TYPE" CHECK("modifiedBy" IS NOT NULL)
;;

ALTER TABLE "DATASET_TYPE"
  ADD CONSTRAINT "fk1_DATASET_TYPE" FOREIGN KEY ("projectFK") REFERENCES "PROJECT" ("id") ON DELETE CASCADE
;;

CREATE SEQUENCE "seq_DATASET_TYPE"
  START WITH 1 INCREMENT BY 1 CACHE 10
;;

CREATE TRIGGER "trig1_DATASET_TYPE"
  BEFORE INSERT ON "DATASET_TYPE"
  FOR EACH ROW
  BEGIN
    SELECT "seq_DATASET_TYPE".NEXTVAL INTO :NEW."id" FROM dual;
  END;
;;

CREATE TRIGGER "trig2_DATASET_TYPE"
  BEFORE UPDATE ON "DATASET_TYPE"
  FOR EACH ROW
  BEGIN
    :NEW."modified" := SYSDATE;
  END;
;;

-----------------------------------------------------------------------------

CREATE TABLE "FILE_TYPE" (
  "id" NUMBER(*, 0),
  "projectFK" NUMBER(*, 0),
  "name" VARCHAR2(128),
  "description" VARCHAR2(512),
  "created" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "createdBy" VARCHAR2(128),
  "modified" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "modifiedBy" VARCHAR2(128)
);;

ALTER TABLE "FILE_TYPE"
  ADD CONSTRAINT "pk1_FILE_TYPE" PRIMARY KEY ("id")
;;

ALTER TABLE "FILE_TYPE"
  ADD CONSTRAINT "ck1_FILE_TYPE" CHECK("id" IS NOT NULL)
;;

ALTER TABLE "FILE_TYPE"
  ADD CONSTRAINT "ck2_FILE_TYPE" CHECK("name" IS NOT NULL)
;;

ALTER TABLE "FILE_TYPE"
  ADD CONSTRAINT "ck3_FILE_TYPE" CHECK("created" IS NOT NULL)
;;

ALTER TABLE "FILE_TYPE"
  ADD CONSTRAINT "ck4_FILE_TYPE" CHECK("createdBy" IS NOT NULL)
;;

ALTER TABLE "FILE_TYPE"
  ADD CONSTRAINT "ck5_FILE_TYPE" CHECK("modified" IS NOT NULL)
;;

ALTER TABLE "FILE_TYPE"
  ADD CONSTRAINT "ck6_FILE_TYPE" CHECK("modifiedBy" IS NOT NULL)
;;

ALTER TABLE "FILE_TYPE"
  ADD CONSTRAINT "fk1_FILE_TYPE" FOREIGN KEY ("projectFK") REFERENCES "PROJECT" ("id") ON DELETE CASCADE
;;


CREATE SEQUENCE "seq_FILE_TYPE"
  START WITH 1 INCREMENT BY 1 CACHE 10
;;

CREATE TRIGGER "trig1_FILE_TYPE"
  BEFORE INSERT ON "FILE_TYPE"
  FOR EACH ROW
  BEGIN
    SELECT "seq_FILE_TYPE".NEXTVAL INTO :NEW."id" FROM dual;
  END;
;;

CREATE TRIGGER "trig2_FILE_TYPE"
  BEFORE UPDATE ON "FILE_TYPE"
  FOR EACH ROW
  BEGIN
    :NEW."modified" := SYSDATE;
  END;
;;

-----------------------------------------------------------------------------

CREATE TABLE "DATASET" (
  "id" NUMBER(*, 0),
  "projectFK" NUMBER(*, 0),
  "typeFK" NUMBER(*, 0),
  "name" VARCHAR2(512),
  "valid" NUMBER(1) DEFAULT 1,
  "created" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "createdBy" VARCHAR2(128),
  "modified" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "modifiedBy" VARCHAR2(128)
);;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "pk1_DATASET" PRIMARY KEY ("id")
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "uk1_DATASET" UNIQUE ("name","projectFK")
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "ck1_DATASET" CHECK("id" IS NOT NULL)
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "ck2_DATASET" CHECK("projectFK" IS NOT NULL)
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "ck3_DATASET" CHECK("typeFK" IS NOT NULL)
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "ck4_DATASET" CHECK("created" IS NOT NULL)
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "ck5_DATASET" CHECK("createdBy" IS NOT NULL)
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "ck6_DATASET" CHECK("modified" IS NOT NULL)
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "ck7_DATASET" CHECK("modifiedBy" IS NOT NULL)
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "fk1_DATASET" FOREIGN KEY ("projectFK") REFERENCES "PROJECT" ("id") ON DELETE CASCADE
;;

ALTER TABLE "DATASET"
  ADD CONSTRAINT "fk2_DATASET" FOREIGN KEY ("typeFK") REFERENCES "DATASET_TYPE" ("id") ON DELETE CASCADE
;;

CREATE SEQUENCE "seq_DATASET"
  START WITH 1 INCREMENT BY 1 CACHE 10
;;

CREATE TRIGGER "trig1_DATASET"
  BEFORE INSERT ON "DATASET"
  FOR EACH ROW
  BEGIN
    SELECT "seq_DATASET".NEXTVAL INTO :NEW."id" FROM dual;
  END;
;;

CREATE TRIGGER "trig2_DATASET"
  BEFORE UPDATE ON "DATASET"
  FOR EACH ROW
  BEGIN
    :NEW."modified" := SYSDATE;
  END;
;;

-----------------------------------------------------------------------------

CREATE TABLE "FILE" (
  "id" NUMBER(*, 0),
  "typeFK" NUMBER(*, 0),
  "name" VARCHAR2(512),
  "size" NUMBER(*, 0),
  "created" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "createdBy" VARCHAR2(128),
  "modified" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "modifiedBy" VARCHAR2(128)
);;

ALTER TABLE "FILE"
  ADD CONSTRAINT "pk1_FILE" PRIMARY KEY ("id")
;;

ALTER TABLE "FILE"
  ADD CONSTRAINT "uk1_FILE" UNIQUE ("name")
;;

ALTER TABLE "FILE"
  ADD CONSTRAINT "ck1_FILE" CHECK("id" IS NOT NULL)
;;

ALTER TABLE "FILE"
  ADD CONSTRAINT "ck2_FILE" CHECK("typeFK" IS NOT NULL)
;;

ALTER TABLE "FILE"
  ADD CONSTRAINT "ck3_FILE" CHECK("created" IS NOT NULL)
;;

ALTER TABLE "FILE"
  ADD CONSTRAINT "ck4_FILE" CHECK("createdBy" IS NOT NULL)
;;

ALTER TABLE "FILE"
  ADD CONSTRAINT "ck5_FILE" CHECK("modified" IS NOT NULL)
;;

ALTER TABLE "FILE"
  ADD CONSTRAINT "ck6_FILE" CHECK("modifiedBy" IS NOT NULL)
;;

ALTER TABLE "FILE"
  ADD CONSTRAINT "fk1_FILE" FOREIGN KEY ("typeFK") REFERENCES "FILE_TYPE" ("id") ON DELETE CASCADE
;;

CREATE SEQUENCE "seq_FILE"
  START WITH 1 INCREMENT BY 1 CACHE 10
;;

CREATE TRIGGER "trig1_FILE"
  BEFORE INSERT ON "FILE"
  FOR EACH ROW
  BEGIN
    SELECT "seq_FILE".NEXTVAL INTO :NEW."id" FROM dual;
  END;
;;

CREATE TRIGGER "trig2_FILE"
  BEFORE UPDATE ON "FILE"
  FOR EACH ROW
  BEGIN
    :NEW."modified" := SYSDATE;
  END;
;;

-----------------------------------------------------------------------------

CREATE TABLE "DATASET_FILE_BRIDGE" (
  "id" NUMBER(*, 0),
  "datasetFK" NUMBER(*, 0),
  "fileFK" NUMBER(*, 0),
  "comment" VARCHAR2(512),
  "created" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "createdBy" VARCHAR2(128),
  "modified" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "modifiedBy" VARCHAR2(128)
);;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "pk1_DATASET_FILE_BRIDGE" PRIMARY KEY ("id")
;;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "uk1_DATASET_FILE_BRIDGE" UNIQUE ("datasetFK","fileFK")
;;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "ck1_DATASET_FILE_BRIDGE" CHECK("id" IS NOT NULL)
;;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "ck2_DATASET_FILE_BRIDGE" CHECK("datasetFK" IS NOT NULL)
;;


ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "ck3_DATASET_FILE_BRIDGE" CHECK("fileFK" IS NOT NULL)
;;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "ck4_DATASET_FILE_BRIDGE" CHECK("createdBy" IS NOT NULL)
;;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "ck5_DATASET_FILE_BRIDGE" CHECK("modified" IS NOT NULL)
;;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "ck6_DATASET_FILE_BRIDGE" CHECK("modifiedBy" IS NOT NULL)
;;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "fk1_DATASET_FILE_BRIDGE" FOREIGN KEY ("datasetFK") REFERENCES "DATASET" ("id") ON DELETE CASCADE
;;

ALTER TABLE "DATASET_FILE_BRIDGE"
  ADD CONSTRAINT "fk2_DATASET_FILE_BRIDGE" FOREIGN KEY ("fileFK") REFERENCES "FILE" ("id") ON DELETE CASCADE
;;

CREATE SEQUENCE "seq_DATASET_FILE_BRIDGE"
  START WITH 1 INCREMENT BY 1 CACHE 10
;;

CREATE TRIGGER "trig1_DATASET_FILE_BRIDGE"
  BEFORE INSERT ON "DATASET_FILE_BRIDGE"
  FOR EACH ROW
  BEGIN
    SELECT "seq_DATASET_FILE_BRIDGE".NEXTVAL INTO :NEW."id" FROM dual;
  END;
;;

CREATE TRIGGER "trig2_DATASET_FILE_BRIDGE"
  BEFORE UPDATE ON "DATASET_FILE_BRIDGE"
  FOR EACH ROW
  BEGIN
    :NEW."modified" := SYSDATE;
  END;
;;

-----------------------------------------------------------------------------

CREATE TABLE "DATASET_GRAPH" (
  "id" NUMBER(*, 0),
  "sourceFK" NUMBER(*, 0),
  "destinationFK" NUMBER(*, 0),
  "comment" VARCHAR2(512),
  "created" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "createdBy" VARCHAR2(128),
  "modified" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "modifiedBy" VARCHAR2(128)
);;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "pk1_DATASET_GRAPH" PRIMARY KEY ("id")
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "uk1_DATASET_GRAPH" UNIQUE ("sourceFK","destinationFK")
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "ck1_DATASET_GRAPH" CHECK("id" IS NOT NULL)
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "ck2_DATASET_GRAPH" CHECK("sourceFK" IS NOT NULL)
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "ck3_DATASET_GRAPH" CHECK("destinationFK" IS NOT NULL)
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "ck4_DATASET_GRAPH" CHECK("createdBy" IS NOT NULL)
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "ck5_DATASET_GRAPH" CHECK("modified" IS NOT NULL)
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "ck6_DATASET_GRAPH" CHECK("modifiedBy" IS NOT NULL)
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "fk1_DATASET_GRAPH" FOREIGN KEY ("sourceFK") REFERENCES "DATASET" ("id") ON DELETE CASCADE
;;

ALTER TABLE "DATASET_GRAPH"
  ADD CONSTRAINT "fk2_DATASET_GRAPH" FOREIGN KEY ("destinationFK") REFERENCES "DATASET" ("id") ON DELETE CASCADE
;;

CREATE SEQUENCE "seq_DATASET_GRAPH"
  START WITH 1 INCREMENT BY 1 CACHE 10
;;

CREATE TRIGGER "trig1_DATASET_GRAPH"
  BEFORE INSERT ON "DATASET_GRAPH"
  FOR EACH ROW
  BEGIN
    SELECT "seq_DATASET_GRAPH".NEXTVAL INTO :NEW."id" FROM dual;
  END;
;;

CREATE TRIGGER "trig2_DATASET_GRAPH"
  BEFORE UPDATE ON "DATASET_GRAPH"
  FOR EACH ROW
  BEGIN
    :NEW."modified" := SYSDATE;
  END;
;;

-----------------------------------------------------------------------------


CREATE TABLE "DATASET_PARAM" (
  "id" NUMBER(*, 0),
  "datasetFK" NUMBER(*, 0),
  "name" VARCHAR2(128),
  "type" VARCHAR2(128),
  "intValue" NUMBER(*, 0) DEFAULT NULL,
  "floatValue" FLOAT DEFAULT NULL,
  "stringValue" VARCHAR2(512) DEFAULT NULL,
  "timestampValue" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "booleanValue" NUMBER (1) DEFAULT NULL,
  "created" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "createdBy" VARCHAR2(128),
  "modified" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "modifiedBy" VARCHAR2(128)
);;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "pk1_DATASET_PARAM" PRIMARY KEY ("id")
;;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "uk1_DATASET_PARAM" UNIQUE ("name","datasetFK")
;;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "ck1_DATASET_PARAM" CHECK("id" IS NOT NULL)
;;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "ck2_DATASET_PARAM" CHECK("name" IS NOT NULL)
;;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "ck3_DATASET_PARAM" CHECK("created" IS NOT NULL)
;;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "ck4_DATASET_PARAM" CHECK("createdBy" IS NOT NULL)
;;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "ck5_DATASET_PARAM" CHECK("modified" IS NOT NULL)
;;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "ck6_DATASET_PARAM" CHECK("modifiedBy" IS NOT NULL)
;;

ALTER TABLE "DATASET_PARAM"
  ADD CONSTRAINT "fk1_DATASET_PARAM" FOREIGN KEY ("datasetFK") REFERENCES "DATASET" ("id") ON DELETE CASCADE
;;

CREATE SEQUENCE "seq_DATASET_PARAM"
  START WITH 1 INCREMENT BY 1 CACHE 10
;;

CREATE TRIGGER "trig1_DATASET_PARAM"
  BEFORE INSERT ON "DATASET_PARAM"
  FOR EACH ROW
  BEGIN
    SELECT "seq_DATASET_PARAM".NEXTVAL INTO :NEW."id" FROM dual;
  END;
;;

CREATE TRIGGER "trig2_DATASET_PARAM"
  BEFORE UPDATE ON "DATASET_PARAM"
  FOR EACH ROW
  BEGIN
    :NEW."modified" := SYSDATE;
  END;
;;

-----------------------------------------------------------------------------

CREATE VIEW "FILE_VIEW" AS 
  SELECT "DATASET_FILE_BRIDGE"."id" AS "id", "PROJECT"."name" AS "projectName", "DATASET"."name" AS "datasetName",  "FILE"."name" AS "fileName"
  FROM "PROJECT", "DATASET", "FILE", "DATASET_FILE_BRIDGE"
  WHERE "DATASET"."projectFK" = "PROJECT"."id"
  AND "DATASET_FILE_BRIDGE"."datasetFK" = "DATASET"."id"
  AND "DATASET_FILE_BRIDGE"."fileFK" = "FILE"."id"
;;

-----------------------------------------------------------------------------

